### PR TITLE
Local time conversion link

### LINKED ISSUE #60: Include a link to a website showing the event on user's local time
[Example](https://www.inyourowntime.zone/2021-03-27_18.30_Europe.Amsterdam)

Could be shown on the first line of description, for example

### PR DESCRIPTION
**Pull request by MaxKosi**
closes #60

### CODE REVIEW

**Comment by Gehock** [comment]
What's the status of this? It currently marked as a draft

**Comment by MaxKosi** [comment]
> What's the status of this? It currently marked as a draft

Ahh Sorry i'm currently extremely busy with my exam project - so I completely forgot about this. Ill check it but actually think that should be done

**Comment by MaxKosi** [comment]
Rebased and ready for Review (I hope)

**Comment by MaxKosi** [comment]
It's showing the changed files of the rebase as well. Did I fuck up _**again**_?

**Comment by Gehock** [comment]
> It's showing the changed files of the rebase as well.
You'll have to rebase the changes and do a force-push to the branch, not a merge

**Comment by MaxKosi** [comment]
Yeah I dont know why I always merge after that. It is pushed now. But the commits exist twice now because of that. Needs some cleaning...

**Comment by Gehock** [comment]
Something funny still happening here, this PR seems to revert most of the changes from #71

**Comment by MaxKosi** [comment]
You are right, and I found the issue. I shouldnt have renamed but added a second var

**Comment by MaxKosi** [comment]
I would change Line 217
https://github.com/zeusops/operationbot/blob/2d1c24accafaafb3ecda17e35e27847ae3193f88/event.py#L217
to this:
`self.title, self.date.strftime(f"%a %Y-%m-%d - %H:%M {cfg.TIME_ZONE}"))`

and readd the TIME_ZONE back to the config file.

**Comment by Gehock** [comment]
Squashed instead of just merging because there was a lot of back and forth in the commits, resulting in a fairly small set of changes.

**Pull request merged**
